chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.main, name='main_page'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('chat/', views.chat_view, name='chat'),
    path('chat/change_avatar/', views.change_avatar, name='change_avatar'),
    path('chat/change_status/', views.change_status, name='change_status'),
]

webchat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.dispatch import receiver
from django.db.models.signals import post_save

User = get_user_model()


def user_avatar_path(instance, filename):
    return f"avatars/{instance.user.username}/{filename}"


class Profile(models.Model):
    """ Модель профиля для каждого пользователя """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to=user_avatar_path, default='avatars/default-avatar.png')
    status = models.CharField(max_length=50, blank=True, default='')

    def __str__(self):
        return f"{self.user} profile"


class ThreadManager(models.Manager):
    """ Менеджер объектов для Thread"""
    def by_user(self, **kwargs):
        user = kwargs.get('user')
        lookup = Q(first_person=user) | Q(second_person=user)
        qs = self.get_queryset().filter(lookup).distinct()
        return qs


class Thread(models.Model):
    """ Модель чата """
    first_person = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True,
                                     related_name='thread_first_person')
    second_person = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True,
                                      related_name='thread_second_person')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    class Meta:
        unique_together = ['first_person', 'second_person']


class ChatMessage(models.Model):
    """ Модель сообщения """
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.CASCADE,
                               related_name='chatmessage_thread')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    # Создает профиль пользователя, когда пользователь регистрируется на сайте
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=ChatMessage)
def update_created_at(sender, instance, created, **kwargs):
    # Обновляет поле Thread updated на значение, когда было создано последнее сообщение
    if created:
        instance.thread.updated = instance.timestamp
        instance.thread.save()

chat/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class UserRegisterForm(UserCreationForm):
    """ Форма регистрации """
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(
        attrs={'class': 'form-input', 'placeholder': 'Имя пользователя'}
        ))
    
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(
        attrs={'class': 'form-input', 'placeholder': 'Пароль'}
        ))

    password2 = forms.CharField(label='Пароль еще раз', widget=forms.PasswordInput(
        attrs={'class': 'form-input', 'placeholder': 'Пароль еще раз'}
        ))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class UserLoginForm(AuthenticationForm):
    """ Форма авторизации"""
    username = forms.CharField(label='Username', widget=forms.TextInput(
        attrs={'class': 'form-input', 'placeholder': 'Имя пользователя'}
        ))

    password = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'class': 'form-input', 'placeholder': 'Пароль'}
        ))

chat/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView
from django.contrib.auth import logout, login
from .forms import UserRegisterForm, UserLoginForm
from django.contrib.auth.decorators import login_required
from . import models, utils


def main(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse_lazy('chat:chat'))
    else:
        return HttpResponseRedirect(reverse_lazy('chat:login'))


class RegisterView(CreateView):
    """ Представление для регистрации """
    template_name = 'registration/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('chat:main_page')
    
    def form_valid(self, form):
        """ Сохранение зарегистрированного пользователя """
        user = form.save()
        login(self.request, user)

        return redirect('chat:chat')


class LoginUser(LoginView):
    """ Представление для входа """
    form_class = UserLoginForm


def logout_user(request):
    """Представление для выхода"""
    logout(request)
    return redirect('chat:login')


@login_required
def change_avatar(request):
    """ Представление для смены аватара, используется в AJAX"""
    if request.method == 'POST' and utils.is_ajax(request=request):
        avatar_file = request.FILES['file']
        
        profile = request.user.profile 
        profile.avatar.save(avatar_file.name, avatar_file)
        profile.save()

        return JsonResponse({'url': profile.avatar.url})
    

@login_required
def change_status(request):
    """ Представление для смены статуса, используется в AJAX"""
    if request.method == 'POST' and utils.is_ajax(request=request):
        new_status = request.POST.get('new-status', '')
        
        profile = request.user.profile
        profile.status = new_status
        profile.save()

        return JsonResponse({})


@login_required
def chat_view(request):
    user_profile = models.Profile.objects.get(user=request.user)
    return render(request, 'chat/chat.html', context={'profile': user_profile})

chat/templates/chat/chat.html
<head>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'chat/css/chat.css' %}">
    <link rel="shortcut icon" href="{% static 'chat/img/logo_icon.png' %}">
    <title>Chat</title>
</head>
<body style='overflow:hidden;'>
    <input type="hidden" value="{{ user.id }}" id="logged-in-user">
    <div class="blur hidden"></div>
    <div class="messager-area">
        <div class="actions">
            <a class="settings"><i class="bi bi-gear"></i></a>
            <a class="logout" href="{% url 'chat:logout' %}"><i class="bi bi-box-arrow-in-left"></i></a>
        </div>
        <div class="interlocutors">
            <input class="interlocutors-search" type="text" placeholder=" 🔍 Поиск собеседника..." style="font-family:Arial, FontAwesome">
            <div class="interlocutors-items">
            </div>
        </div>
        <div class="main-body">
            <center>Выбери чат, чтобы начать общение!</center>
        </div>
    </div>
    <div class="settings-menu hidden">
        <div class="close-settings"><i class="bi bi-x-lg"></i></div>
        <div class="logged-in-user-upper">
            <div class="logged-in-user-img" title="Установить аватар">
                <img src="{{ profile.avatar.url }}" id="avatar-image">
                <form id="avatar-form" enctype="multipart/form-data" method="post" style="display:none;" action="{% url 'chat:change_avatar' %}">
                    {% csrf_token %}
                    <input type="file" name="file" id="avatar-input" accept="image/*">
                </form>
            </div>
            <div class="logged-in-user-username">{{ request.user }}</div>
        </div>
        <div class="logged-in-user-status">
            <form method="post" id="status-form" action="{% url 'chat:change_status' %}">
                {% csrf_token %}
                <p>Установить статус</p>
                <textarea id='status-value' name="new-status" maxlength="50">{{ profile.status }}</textarea>
                <i class="bi bi-check confirm-status"></i>
            </form>
        </div>
    </div>
    <div class="successfully hidden">Успешно.</div>
    <div class="unsuccessfully hidden">Произошла ошибка.</div>
</body>
<script src="{% static 'chat/js/chat.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'chat/js/settings.js' %}"></script>